### ISSUE TITLE
Unable to disable loading of modules in BootstrapperContainerBase

### ISSUE THREAD

**Issue by dmitrybublik** [LogoFX/LogoFX#11]
1) There is the need of adding possibility of switching off loading of modules in bootstrapper.

**Comment by godrose** [comment]
The second issue (incompatible dll loading) is related to the inner package - Solid.Composition.
Moving it there

**Comment by godrose** [comment]
The loading of composition modules is tightly coupled to the assemblies loading for C.Micro.
This coupling should be resolved.
One way is use convention for loading Presentation Layer assemblies:
Only those that contain "Gui", "UI", "Presentation" would be loaded in the run-time. This convention can be expanded via a convention manager of some kind.
Need to distinguish between the following use cases:
1) Composition Module - need to register dependencies into the IoC container, initialize some object.
2) Shared Library - source of View Models and Views.
3) UI Module - combines the two and adds UI Module aspect. The UI Modules are currently in the same pipeline as the Composition Modules. This is fine as the UI Modules **always** contain a Root View Model which should be resolved from the IoC Container.

**Comment by godrose** [comment]
Fixed.
