### ISSUE TITLE
Cleanup IModel interface

### ISSUE THREAD

**Issue by glyad** [LogoFX/LogoFX#5]
IMHO, the basic IModel interface mast include GetHashCode() method and inherit the INPC interface. So, we will be able to inherit entity or value object interface from. 

Possible IModel aspects:
1. IHaveId<T> - IEntityIModel
2. IIsDirty - IEntityModel
3. IUndo - IEntityModel
4  IRedo - IEntityModel
5. IDataErrorInfo - IModel
6. INotifyPropertyChanged - IModel
7. IEditableObject - IEntityModel

... and default implementations as well. :)

**Comment by godrose** [comment]
won't fix.
